name: actorcheck

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/6 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@master
      - name: Set git username and email
        run: |
          # 
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com" 
          git config --global user.name "${GH_USERNAME}" 
        env: 
          GH_USERNAME: ${{ github.event.schedule.user.login }}
