name: addhost
on: [push]
  
jobs:
  addhost:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: add host
        run: |
          sudo echo "172.16.18.16  www.example.com example" >> /etc/hosts
      - name: check host
        run: |
          sudo cat /etc/hosts
