name: Checkpyenv.yaml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: get pyenv
        run: |
          git clone https://github.com/pyenv/pyenv.git .pyenv
      - name: check
        run: |
          ls -adl .pyenv
      - name: setting
        run: |
          ./setup.sh
          pyenv
