name: Using
on: [push]

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python version
      uses: gabrielfalcao/pyenv-action@v5
      with:
        default: 3.8.2
    - name: List python versions
      run: pyenv versions
    - name: check env
      run: |
        env
    - name: check path
      run: |
        echo $PATH
    - name: cat 
      run: |
        cat ~/.bashrc
