name: Using2
on: [push]

jobs:
  my_python_job:
    name: "Python"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check path
      run: |
        echo $PATH
    - name: add path
      run: 
        echo "::add-path::"/opt/hostedtoolcache/pyenv_root/1.2.17/x64/shims:/opt/hostedtoolcache/pyenv_root/1.2.17/x64/bin""
    - name: check path2
      run: |
        echo $PATH
