name: checkartifacts
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkartifactsid
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
          curl -s -u admin:${{ secrets.GITHUB_TOKEN }} $URL |jq '.artifacts[].id'
          ids=$(curl -s -u admin:${{ secrets.GITHUB_TOKEN }} $URL |jq '.artifacts[].id')
      - name: find lasted id
        run: |
          echo $ids
          max=ids[0]
          for id in $ids
          do
            if [ $max -lt $id ]
            then
                max=$id
            fi
          done
          echo "最大值为: $max"
