name: tagcheck
on: [push]
    
jobs:
  build:
    name: build-electron-from-react-web
#    env:
#      VERSION: 1.0.1

    # update versions below
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
 #       include:
 #         - os: ubuntu-latest
 #           artifact_name: book-package-app_1.0.1_amd64.deb
 #           asset_name: book-package-app_1.0.1_amd64.deb
 #         - os: windows-latest
 #           artifact_name: "book-package-app Setup 1.0.1.exe"
 #          asset_name: "book-package-app Setup 1.0.1.exe"
 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get tag version
        shell: bash
        run: |
          version=1.0.1   # get the tag version
          echo $version
      - name: set artifact&asset name for ubuntu
        if: runner.os=='linux'
        run: |
          version=1.0.1
          echo "::set-env name=artifactname::book-package-app_${version}_amd64.deb"
          echo "::set-env name=assetname::book-package-app_${version}_amd64.deb"
      - name: set artifact&asset name for windows
        shell: bash
        if: runner.os=='windows'
        run: |
          echo "::set-env name=artifactname::book-package-app Setup ${version}.exe"
          echo "::set-env name=assetname::book-package-app Setup {$version}.exe"        
      - name: checkvalue
        run: |
          echo $artifactname
          echo $assetname
