name: checkoutBrepo
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: 'weide-zhou/ticket17'
      - name: check files
        run: |
          ls -al
          cd gradlefolder
          cat test.txt
      - uses: actions/setup-java@v1
        with:
          java-version: 11 
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: gradlefolder
