name: checkout
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: check
        run: |
          git branch
      
      - name: check2
        run: |
          git fetch --prune --tags
