name: checkout
on: 
  push:
    tags: 
      - 'v*'
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      
      - name: check2
        run: |
          git tag
  #        git fetch --prune --unshallow --tags
  #        echo "REF: ${{ github.ref }}"
