name: commitfiles
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
 #       with:
 #         persist-credential: false
      - name: Modify value
        run: |
          echo 'Add value5' >> testfile.txt
      - name: move to dir
        run: |
          mkdir -p output
          yes| cp -rf testfile.txt ./output/
      - name: Commit files
        run: |
          git config --local user.email "weide-zhou@outlook.com"
          git config --local user.name "weide-zhou"
          git add ./output
          git commit -m "Signcheck5"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: B77
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
