name: conditional job
on: [push]
jobs:
  conditionaljob:
    runs-on: [ubuntu-latest]
    steps:
          
      - name: getstatus
        run: |
          exit 0
      - name: Dump job context
        if: always()
        run: |
          echo ${{ job.status }}
