name: conditional job
on: [push]
jobs:
  conditionaljob:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo step1
      - name: step2
        run: |
          echo step2
      - name: step3
        run: |
          echo step3
