name: conditional job
on: [push]
jobs:
  conditionaljob:
    runs-on: [ubuntu-latest]
    steps:
          
      - name: getstatus
        id: step1
        run: |
          echo "::set-output name=status::fail"

      - name: step3
        if:  $step1status == 'fail'
        run: |
          echo step3
        env: 
          step1status: ${{ steps.step1.outputs.status }}
