name: conditional job
on: [push]
jobs:
  conditionaljob:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        continue-on-error: true
        id: step1
        run: |
          echo step1
      - name: step1status
        run: |
          echo ${{ steps.step1.status }}
      - name: step2
        run: |
          echo step2
      - name: step3
        run: |
          echo step3
