name: conditional job
on: [push]
jobs:
  conditionaljob:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        continue-on-error: true
        run: |
          echo step1
          
      - name: getstatus
        if: failure()
        id: step1
        run: |
          echo "::set-output name=status::fail"

      - name: step2
        continue-on-error: true
        run: |
          echo step2
          
      - name: getstatus
        if: failure()
        id: step2
        run: |
          echo "::set-output name=status::fail"
      
      - name: step3
        if: steps.step1.outputs.status == fail || steps.step2.outputs.status == fail
        run: |
          echo step3
