name: dbtest
on: push
  
env:
    TZ: Europe/Paris
    PHP_VERSION: 7.4
    NODE_VERSION: 10.x
    COMPOSER_ALLOW_SUPERUSER: '1' # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

    # Database
    MYSQL_USER: tester
    MYSQL_ROOT_PASSWORD: symfony
    MYSQL_DATABASE: symfony


jobs:
    php:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mariadb:10.4
                ports:
                  - 3306/tcp
                options: --health-cmd="mysqladmin ping"
      #          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10 
        steps:
          - name: test
            run: |
              echo test
