name: staging
on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging

env:
  TEST: ONE

jobs:

  plan:
    name: Run terraform plan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      env:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run plan
        run: |
          cd environments/staging
          terraform plan
