name: Develop Push Docker Image

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - uses: actions/checkout@v1
        with:
          ref: B8
          path: src/github.com/${{ github.repository }}
      - name: echo env
        run: |
          echo $(go env GOPATH)
          echo $(go env GOROOT)
          ls -al
#      - run: go get -v -u github.com/sirupsen/logrus
      - name: go get
        run: go get -v -u ./...

#        working-directory: $GOPATH

      
      - run: go build -ldflags "-X main._buildDate=testDate -X main._buildVersion=testVersion" -o main *.go
      
      - run: docker build . --tag <removed>

      - run: docker login -u <removed> -p ${{ secrets.DockerHubPassword }}

      - run: docker push <removed>
