name: Develop Push Docker Image

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - uses: actions/checkout@v1
        with:
          ref: B8
          path: src/github.com/${{ github.repository }}
      - name: echo env
        run: |
          echo $(go env GOPATH)
          echo $(go env GOROOT)
          echo $PATH
          ls -al
#      - run: go get -v -u github.com/sirupsen/logrus
      - name: go get
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          go get -v -u ./...

