name: gotify
on: [push]
env:
  gotifydownloadurl: https://github.com/gotify/server/releases/download/v2.0.14
  
jobs:
  gotify:
    strategy:
      matrix:
        platform: [windows-amd64.exe, linux-amd64]
    runs-on: [windows-latest]
    steps:
      - name: download the zip file
        shell: bash
        run: |
          curl -O $gotifydownloadurl/gotify-${{ matrix.platform }}.zip
          ls -al
      - name: unzip files
        shell: bash
        run: |
          unzip gotify-${{ matrix.platform }}.zip
          ls -al
      - name: install
        shell: bash
        run: |
          chmod +x gotify-${{ matrix.platform }}
          sudo ./gotify-${{ matrix.platform }}
