name: gotify
on: [push]
env:
  gotifydownloadurl: https://github.com/gotify/server/releases/download/v2.0.14
  
jobs:
  gotify:
    strategy:
      matrix:
        os: [ubuntu-latest]
 #       os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            build: windows-amd64.exe
          - os: ubuntu-latest
            build: linux-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: download the zip file
        shell: bash
        run: |
          curl -L -O $gotifydownloadurl/gotify-${{ matrix.build }}.zip
          ls -al
      - name: unzip files
        shell: bash
        run: |
          unzip gotify-${{ matrix.build }}.zip
          ls -al
      - name: install on windows
        if: runner.os == 'Windows'
        shell: bash
        run: |
          chmod +x gotify-${{ matrix.build }}
          ./gotify-${{ matrix.build }}
      - name: install on linux
        if: runner.os == 'Linux'
        shell: bash
        run: |
          chmod +x gotify-${{ matrix.build }}
          sudo ./gotify-${{ matrix.build }}
