name: jsonvariable
on: 
  issues:
    types: demilestoned
  
jobs:
  jsonvariable:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: getjsonvar
        run: |
          script.sh ${{ secrets.json }}
