name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 6 + 1 > test-homework.txt
          expr 3 + 7 > math-homework.txt
          mkdir src
          mv math-homework.txt ./src
          mv test-homework.txt ./src
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: ./src

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - name: check files
        run: |
          ls -al
      - shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          echo $value


