name: change lfs exclude

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        lfs: true
    - name: Run a one-line script
      run: git config --unset lfs.fetchexclude
