name: change lfs exclude

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: check git config before checkout
      run: |
        git config -l
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: check git config after checkout
      run: |
        git config -l
    - name: Run a one-line script
      run: |
        git config lfs.fetchexclude "media/excessive"
#        git config --unset lfs.fetchexclude
    - name: check git config
      run: |
        git config -l
    - name: unset
      run: |
        git config --unset lfs.fetchexclude
    - name: check git config2
      run: |
        git config -l
