name: change lfs exclude
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: cat git config
      run: |
        cd .git
        cat config
    - name: Set the lfs.fetchexclude
      run: |
        git config lfs.fetchexclude "media/excessive"
    - name: cat git config
      run: |
        cd .git
        cat config
    - name: check git config after checkout
      run: |
        git config -l
    - name: unset
      run: |
        git config --unset lfs.fetchexclude
    - name: check git config after unset
      run: |
        git config -l
