name: secretinvoke
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v2
      - name: execute
        run: |
          sh gitssh.sh
        env:
          token: ${{ secrets.PAT3 }}
      - name: check files
        run: |
          ls -al
      - name: ping 
        run: |
          ping -c 5 vsaspnetmvcapp.scm.azurewebsites.net
