name: checkaction
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: action
        uses: maharishi1/DC-vs-Marvel@gii
