name: test
on: [push]
jobs:
  job1:
    name: test
    runs-on: ubuntu-latest 
    if: github.ref=='master'
    steps:
      - run: echo test
    
    

#jobs:
#  tsc:
#    name: tsc
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: install node v12
#      uses: actions/setup-node@v1
#      with:
#        node-version: 12
#    - name: yarn install
#      run: yarn install
#    - name: tsc
#      uses: icrawl/action-tsc@v1
    - name: delete declaration files
      if: failure() || success()
      run: |
        echo test
