name: milestone
on: 
  pull_request:
    types: [closed]
  
jobs:
  job1:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [6, 8, 10]

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - if: matrix.os=='ubuntu-16.04'
        name: sleep
        run: |
          sleep 20
      - if: matrix.os=='ubuntu-18.04'
        name: failstep
        run: |
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
