name: milestone
on: 
  issues:
    types: demilestoned
  
jobs:
  projectcard:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: add label
        run: |
          curl -H "Accept: application/vnd.github.antiope-preview+json" -d '{"labels":["Needs Milestone"]}' https://api.github.com/repos/weide-zhou/ticket13/issues/6/labels
