name: milestone
on: [push]
  
jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [6, 8, 10]

    steps:
      - if: matrix.os='ubuntu-16.04'
        name: sleep
        run: |
          sleep 20
      - if: matrix.os='ubuntu-18.04'
        name: failstep
        run: |
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
