name: milestone
on: [push]
  
jobs:
  job1:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node: [6, 8]

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - if: matrix.os=='ubuntu-16.04'
        name: sleep
        run: |
          sleep 20
      - if: matrix.os=='ubuntu-18.04'
        name: failstep
        run: |
          exit 1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          
  job2:
    needs: [job1]
    if: always()
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check the jobs
        run: |
          jobstatus=$(curl -X GET -s -u "admin:${{ secrets.PAT3 }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs | jq ".jobs[] | {job_status: .conclusion, matrix: .name}")
          echo $jobstatus
          echo "::set-env name=JOBSTATUS:$jobstatus"
      - name: fail status
        if: contains(env.JOBSTATUS, 'failure')
        run: |
          echo job failed
