name: MinGW
on: [push]

  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo $PATH
      - name: step2
        run: |
          env | grep -i MingW
