name: hostcheck
on: 
  
jobs:
  hostcheck:
    runs-on: [ubuntu-latest]
    steps:
      # wait for it to start up
      - name: timewait
        run: |
          sleep 20
      - name: hostcheck
        run: |
          hostname

