name: test
on: [push]
env:
  OS_VERSION: ubuntu-18.04
  ruby_version: 2.4
  postgres_image: postgres:latest 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: postgres


jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
      - run: |
          echo ${{ env.OS_VERSION }}
