name: deployment
on: [deployment]

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: update deploy status
        if: always()
        uses: unacast/actions-github-deployment-status@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
