name: deployment
on: [deployment]

jobs:
  test:
    runs-on: [windows-latest]
    steps:
      - name: update deploy status
        if: always()
        uses: unacast/actions-github-deployment-status@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          status: failure
      - name: 'deployment success'
        if: always()
        uses: 'deliverybot/deployment-status@v1'
        with:
          state: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}
