name: needscheck
on: [push]
  
jobs:
  job-1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  job2:
    needs: [job-*]
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: echo test
