name: nodesetup
on: [push]
  
jobs:
  nodesetup:
    runs-on: [ubuntu-latest]
    steps:
      - name: nodesetup
        uses: actions/setup-node@v1.4.0
        with:
          node-version: 13
      - name: npmversion
        run: |
          npm version
  job4:
    runs-on: [ubuntu-latest]
    steps:
      - name: set output
        run: echo ::set-output name=ifpublish::'did_not_publish'
        id: check
      - name: skip did not publish commits
        if: steps.check.outputs.ifpublish == 'did_not_publish'
        run: |
          echo test  
