name: outputcheck
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v1
#      - name: Docker build
#        run: ./dockerbuild.sh
      - name: get output value
        id: getimage
        run: |
          echo "::set-output name=tag::$(sh dockerbuild.sh | grep tag2)"
      - name: check the value
        run: |
          echo ${{ steps.getimage.outputs.tag }}
          echo ${${{ steps.getimage.outputs.tag }}#*=}
      - name: check env
        run: |
          env | grep GA_DOCKER_IMAGE
          echo $GA_DOCKER_IMAGE
        
#      - name: Render ECS task definition
#        uses: aws-actions/amazon-ecs-render-task-definition@v1
#          with:
#            task-definition: task-definition.json
#            container-name: stage-web
#            image: <a value from the output of ./dockerbuild.sh here>
