name: tagcheck
on:
  push:
    paths:
      - packages/packagename/**
      - .github/workflows/package-workflow.yaml
    tags:
      - v*

  
jobs:
  projectcard:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: process
        run: |
           env
