name: tagcheck
on:
  push:
    paths:
      - packages/packagename/**
      - .github/workflows/package-workflow.yaml


  
jobs:
  projectcard:
    runs-on: [windows-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: process
        run: |
           env | grep NUMBER_OF_PROCESSORS
      - name: set Number of processors
        run: |
          echo "::set-env name=NUMBER_OF_PROCESSORS::4"
      - name: process2
        run: |
          gci env:* | sort-object name
