name: pathcheck
on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: set pythonpath
        run: |
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/ticket13
          echo $PYTHONPATH
#      - name: add path
#        run: |
#          echo "::add-path::/home/runner/work/ticket13"
#          pwd
