name: pathtag
on:
  push:
    paths:
      - '**/pathtag.yaml'
    tags-ignore:
      - v*
  
jobs:
  job1:
#    if: "!contains(github.ref, 'v')"
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
