name: pathcheck
on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: set pythonpath
        run: |
          export PYTHONPATH=$PYTHONPATH:/home/runner/work/ticket13
          echo $PYTHONPATH
      - name: check path
        run: |
          echo $PYTHONPATH
      - name: add path
        run: |
          echo "::add-path::/home/runner/work/ticket13"
      - name: check2
        run: |
          echo $PATH
      - name: set pythonpath2
        run: |
          echo "::set-env name=pythonpath2::/home/runner/work/ticket13_2"
      - name: check2
        run: |
          echo $pythonpath2
      - name: check3
        run: |
          env | grep python
          
