name: prcheck
on: [pull_request]
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo step1
      - name: new commit
        uses: zwaldowski/git-commit-action@v1
        with:
          commit_message: new commit
          author_name: weide
