name: something
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize


jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        if: contains(github.head_ref, 'feature')
        run: echo test
 #       env:
 #         GITHUB_CONTEXT: ${{ toJson(github) }}
 #       run: echo "$GITHUB_CONTEXT"
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: check files
#        run: |
#          ls -al
#          cat README.md

