name: prcheck
on: [pull_request]
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo step1
      - name: new commit
        uses: EndBug/add-and-commit@v2
        with:
          message: new commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
