name: prcheck
on:
  pull_request:
    types: 
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - edited
      - closed
      - reopened
      - synchronize
      - ready_for_review
      - locked
      - unlocked
      - review_requested
      - review_request_removed


jobs:
  prcheck:
    if: github.event.action == 'labeled' && github.label == runtest
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
 #     - name: Simple commit
 #       run: |
 #         git remote set-url origin https://test:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
 #         git config --global user.name weide
 #         git config --global user.email weide-zhou@outlook.com
 #         git checkout B7
 #         cat 1> file1
 #         git add .
 #         git commit -m 'version1'
 #         git push origin B7:B7
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.PAT }}
