name: prcheck
on:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
  prcheck:
  #  if: github.event.action == 'labeled'
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
 #     - name: Simple commit
 #       run: |
 #         git remote set-url origin https://test:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
 #         git config --global user.name weide
 #         git config --global user.email weide-zhou@outlook.com
 #         git checkout B7
 #         cat 1> file1
 #         git add .
 #         git commit -m 'version1'
 #         git push origin B7:B7
 #       env:
 #         GITHUB_TOKEN: ${{ secrets.PAT }}
