name: PRCheck
on: [pull_request]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v2
      - name: git diff
        run: |
          git diff --name-only ${{ github.ref }}/HEAD origin/master
