name: PRCheck2
on: 
  pull_request:
    types: 
      - opened
      - synchronize
      - edited

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
