name: something
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
     - B121

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        run: echo test
