name: something
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

jobs:
  job1:
    if: contains(github.base_ref, 'feature')
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v2
      - name: check files
        run: |
          ls -al
          cat README.md

