name: something
on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
     - B121

jobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        if: "!contains(github.head_ref, 'feature')"
        run: echo test
