name: prcheck
on: [pull_request]
jobs:
  prcheck:
    runs-on: [ubuntu-latest]
    steps:
      - name: step1
        run: |
          echo step1
      - name: Commit changes
        uses: EndBug/add-and-commit@v2 
        with:
          author_name: Your Name
          author_email: mail@example.com
          message: "Your commit message"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
