name: PRCheck
on: [pull_request]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: checkout
        uses: actions/checkout@v2
   #   - name: git diff
   #     run: |
   #       git branch -r
   #       git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs
   #       git diff --name-only HEAD origin/master
      - name: check pr files
        run: |
          URL="https://api.github.com/repos/&{{github.repository}}/pulls/25/files"
          curl -s -X GET -G $URL | jq -r '.[] | .filename'
