name: publishmultipledockerimage
on: push
#  push:
#    paths: 
#      - '**/Dockerfile'
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get changed files
        id: getfile
        run: |
          echo "::set-env name=files2::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          for i in 'apple' 'meat' 'sleep' 'woman'
          do
              echo I like $i
          done
