name: publishmultipledockerimage
on: push
#  push:
#    paths: 
#      - '**/Dockerfile'
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs | sed 's/[ ][ ]*/,/g')"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

#      - name: echo output
#        run: |
#          for i in $files
#          do
#              echo I like $i
#          done
