name: Test

on:
  push:
    branches: 
      - B142
  pull_request:
    types: 
      - opened
      - edited
      - synchronize
      - closed
jobs:

  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Step 1
        run: |
          echo " Step 1"

      - name: Step 2
        if: github.event.pull_request.merged == true
        run: |
          echo " Step 2"
