name: recreatePR
on: [push]

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: close current PR
        run: |
          curl --request PATCH \
          --url https://api.github.com/repos/${{ github.repository }}/pulls/34 \
          --header 'authorization: Bearer ${{ secrets.PAT3 }}' \
          --data '{"state": "closed"}'
      - name: recreate a pull request
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header 'authorization: Bearer ${{ secrets.PAT3 }}' \
          --data '{
            "title": "New Pull request",
            "body": "Please pull these awesome changes in!",
            "head": "B108",
            "base": "master"
          }'
