name: releasecheck
on: 
  release:
    types: [published, edited]

jobs:
  job1:
    if: "!github.event.release.prerelease"
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo release
