name: repeattrigger
on:
  release:
  push:
    paths: 
      - "*.md"
    tags:
      - "v*"
    
  pull_request:
    paths:
      - "**/*.rs"
      - "Cargo.toml"
 
jobs:
  projectcard:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
