name: RepoAworkflow
on:
  release:
    types: 
      - created
      - edited
  
jobs:
  RepoAjobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo test
      - name: send dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: weide-zhou/Notification
          event-type: release
          client-payload: '{"new_version": "6.3.4"}'
