name: signcommit
on: push
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: test
        run: |
          echo test
      - name: checkstatus
        run: |
          git show --name-status 407a5e88ba80157ecdb6ed6ad464fdc4739c702e
