name: tagcheck
on:
  push:
    tags:
      - 'v*' # any push with a tag in semver format
    
jobs:
  build:
    name: build-electron-from-react-web
#    env:
#      VERSION: 1.0.1

    # update versions below
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
 #       include:
 #         - os: ubuntu-latest
 #           artifact_name: book-package-app_1.0.1_amd64.deb
 #           asset_name: book-package-app_1.0.1_amd64.deb
 #         - os: windows-latest
 #           artifact_name: "book-package-app Setup 1.0.1.exe"
 #          asset_name: "book-package-app Setup 1.0.1.exe"
 
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: get tag version
        run: |
          version=1.0.1   # get the tag version
      - name: set artifact&asset name for ubuntu
        if: runner.os==linux
        run: |
          echo "::set-env name=artifactname::book-package-app_$version_amd64.deb"
          echo "::set-env name=assetname::book-package-app_$version_amd64.deb"
      - name: set artifact&asset name for windows
        if: runner.os==windows
        run: |
          echo "::set-env name=artifactname::book-package-app Setup $version.exe"
          echo "::set-env name=assetname::book-package-app Setup $version.exe"        
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v1-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./electron/dist/$artifactname"
          asset_name: $assetname
          tag: ${{ github.ref }}
          overwrite: true
