name: Module-ABC Release

on:
  release:
    types:
      - published
    tags:
      - '*module-abc*'
    # If this tag is used, a release is created

jobs:
  jobcontent:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          echo test
