name: tagcheck
on:
  push:
    tags:
      - 'v*' # any push with a tag in semver format
    
jobs:
  build:
    name: build-electron-from-react-web
#    env:
#      VERSION: 1.0.1

    # update versions below
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
 #       include:
 #         - os: ubuntu-latest
 #           artifact_name: book-package-app_1.0.1_amd64.deb
 #           asset_name: book-package-app_1.0.1_amd64.deb
 #         - os: windows-latest
 #           artifact_name: "book-package-app Setup 1.0.1.exe"
 #          asset_name: "book-package-app Setup 1.0.1.exe"
 
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check tag version
        run: |
          echo ${github.ref##*v}
