name: updatestatus
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: updatestatus
        run: |
          curl -X POST -H 'Content-Type: application/json' --data '{"state": "pending", "target_url": "https://locahost"}' https://${{ secrets.GITHUB_TOKEN}}:x-oauth-basic@api.github.com/repos/${{ github.repository }}/statuses/cf2452fa62dbab943475273482c9a38baac5e180
