name: vcpkgpath
on: [push]
  
jobs:
  job1:
    runs-on: [windows-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check path
        shell: bash
        run: |
          which vcpkg
      - name: test
        shell: bash
        run: |
          env
      - name: test2
        shell: bash
        run: |
          env | grep vcpkg
  
