name: vcpkgpath
on: [push]
  
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check path
        run: |
          which vcpkg
      - name: check2
        run: |
          whereis vcpkg
