name: workflownamecheck
on: [push] 
jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: check workflowname
        run: |
          echo ${{ github.workflow }} 
      - name: check eventname
        run: |
          echo ${{ github.event_name }}   
