name: my workflow
on: push
env:
  MY_WORKFLOW_VAR: work
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo ::set-env name=STEPVAR::${{ env.MY_WORKFLOW_VAR }}-somestep
    - name: Test
      run: echo $STEPVAR
