name: workspace
on: [push]
jobs:
  workspace:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo $GITHUB_WORKSPACE
      - run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(env) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo ${{ env.GITHUB_WORKSPACE }}

      - name: Set env
        run: echo ::set-env name=workspace::$GITHUB_WORKSPACE
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(env) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo $npm_config_cache
        env:
          npm_config_cache: ${{ env.workspace }}/frontend_cache
